stages:
  - build
#  - test
  - deploy

default:
  before_script:
    - apt-get update
    - apt-get install openssh-server -y
    #docker
    - apt-get install ca-certificates curl
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    - chmod a+r /etc/apt/keyrings/docker.asc
    - echo \
    - "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    - $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    - tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt-get update
    - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - eval "$(ssh-agent)"
    - echo "${SSH_KEY}" | ssh-add -

build_docker_image:
  stage: build
  script:
    - docker build -t mituta/digest:latest --platform linux/amd64 .

save_docker_image:
  stage: build
  script:
    - docker save mituta/digest > digest.tar

copy_to_vm:
  stage: deploy
  script:
    - scp digest.tar root@10.90.138.104:~/
#  environment: production

start_service:
  stage: deploy
  script:
    - ssh root@10.90.138.104 docker compose up -d
#  environment: production
