stages:
  - build
  - test
  - deploy

default:
  image:
    name: docker
  before_script:
    - eval "$(ssh-agent)"
    - echo "${SSH_KEY}" | ssh-add -
    - apk add --no-cache python3 py3-pip

build_docker_image:
  stage: build
  script:
    - docker build -t mituta/digest:latest --platform linux/amd64 .

save_docker_image:
  stage: build
  script:
    - docker save mituta/digest > digest.tar

run_unit_tests:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest tests/test_bot_help.py
    - python -m unittest tests/test_bot_settings.py
    - python -m unittest tests/test_bot_start.py
    - python -m unittest tests/test_chose_bot_language.py
    - python -m unittest tests/test_digest_edit.py
    - python -m unittest tests/test_settings_back.py

copy_to_vm:
  stage: deploy
  script:
    - scp digest.tar root@10.90.138.104:~/
#  environment: production

load_on_vm:
  stage: deploy
  script:
  - ssh root@10.90.138.104 docker load < digest.tar

start_service:
  stage: deploy
  script:
    - ssh root@10.90.138.104 docker compose up -d
#  environment: production
