services:
  digest-bot-service:
    image: "digest:latest"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - YGPT_FOLDER_ID=${YGPT_FOLDER_ID}
      - YGPT_TOKEN=${YGPT_TOKEN}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
    volumes:
      - "./resources:/app/resources"
  digest-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=digest-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"